// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuff.proto

#ifndef PROTOBUF_protobuff_2eproto__INCLUDED
#define PROTOBUF_protobuff_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3002000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3002000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
namespace tkJute {
class AcceptJute;
class AcceptJuteDefaultTypeInternal;
extern AcceptJuteDefaultTypeInternal _AcceptJute_default_instance_;
class AcceptReplyJute;
class AcceptReplyJuteDefaultTypeInternal;
extern AcceptReplyJuteDefaultTypeInternal _AcceptReplyJute_default_instance_;
class CommitJute;
class CommitJuteDefaultTypeInternal;
extern CommitJuteDefaultTypeInternal _CommitJute_default_instance_;
class CommitShortJute;
class CommitShortJuteDefaultTypeInternal;
extern CommitShortJuteDefaultTypeInternal _CommitShortJute_default_instance_;
class PreAcceptJute;
class PreAcceptJuteDefaultTypeInternal;
extern PreAcceptJuteDefaultTypeInternal _PreAcceptJute_default_instance_;
class PreAcceptOkJute;
class PreAcceptOkJuteDefaultTypeInternal;
extern PreAcceptOkJuteDefaultTypeInternal _PreAcceptOkJute_default_instance_;
class PreAcceptReplyJute;
class PreAcceptReplyJuteDefaultTypeInternal;
extern PreAcceptReplyJuteDefaultTypeInternal _PreAcceptReplyJute_default_instance_;
class PrepareJute;
class PrepareJuteDefaultTypeInternal;
extern PrepareJuteDefaultTypeInternal _PrepareJute_default_instance_;
class PrepareReplyJute;
class PrepareReplyJuteDefaultTypeInternal;
extern PrepareReplyJuteDefaultTypeInternal _PrepareReplyJute_default_instance_;
class TryPreAcceptJute;
class TryPreAcceptJuteDefaultTypeInternal;
extern TryPreAcceptJuteDefaultTypeInternal _TryPreAcceptJute_default_instance_;
class TryPreAcceptReplyJute;
class TryPreAcceptReplyJuteDefaultTypeInternal;
extern TryPreAcceptReplyJuteDefaultTypeInternal _TryPreAcceptReplyJute_default_instance_;
class tk_command_jute;
class tk_command_juteDefaultTypeInternal;
extern tk_command_juteDefaultTypeInternal _tk_command_jute_default_instance_;
}  // namespace tkJute

namespace tkJute {

namespace protobuf_protobuff_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::uint32 offsets[];
  static void InitDefaultsImpl();
  static void Shutdown();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_protobuff_2eproto

// ===================================================================

class tk_command_jute : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:tkJute.tk_command_jute) */ {
 public:
  tk_command_jute();
  virtual ~tk_command_jute();

  tk_command_jute(const tk_command_jute& from);

  inline tk_command_jute& operator=(const tk_command_jute& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const tk_command_jute& default_instance();

  static inline const tk_command_jute* internal_default_instance() {
    return reinterpret_cast<const tk_command_jute*>(
               &_tk_command_jute_default_instance_);
  }

  void Swap(tk_command_jute* other);

  // implements Message ----------------------------------------------

  inline tk_command_jute* New() const PROTOBUF_FINAL { return New(NULL); }

  tk_command_jute* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const tk_command_jute& from);
  void MergeFrom(const tk_command_jute& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(tk_command_jute* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string key = 2;
  void clear_key();
  static const int kKeyFieldNumber = 2;
  const ::std::string& key() const;
  void set_key(const ::std::string& value);
  #if LANG_CXX11
  void set_key(::std::string&& value);
  #endif
  void set_key(const char* value);
  void set_key(const char* value, size_t size);
  ::std::string* mutable_key();
  ::std::string* release_key();
  void set_allocated_key(::std::string* key);

  // string val = 3;
  void clear_val();
  static const int kValFieldNumber = 3;
  const ::std::string& val() const;
  void set_val(const ::std::string& value);
  #if LANG_CXX11
  void set_val(::std::string&& value);
  #endif
  void set_val(const char* value);
  void set_val(const char* value, size_t size);
  ::std::string* mutable_val();
  ::std::string* release_val();
  void set_allocated_val(::std::string* val);

  // int32 opcode = 1;
  void clear_opcode();
  static const int kOpcodeFieldNumber = 1;
  ::google::protobuf::int32 opcode() const;
  void set_opcode(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:tkJute.tk_command_jute)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr key_;
  ::google::protobuf::internal::ArenaStringPtr val_;
  ::google::protobuf::int32 opcode_;
  mutable int _cached_size_;
  friend struct protobuf_protobuff_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class PrepareJute : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:tkJute.PrepareJute) */ {
 public:
  PrepareJute();
  virtual ~PrepareJute();

  PrepareJute(const PrepareJute& from);

  inline PrepareJute& operator=(const PrepareJute& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const PrepareJute& default_instance();

  static inline const PrepareJute* internal_default_instance() {
    return reinterpret_cast<const PrepareJute*>(
               &_PrepareJute_default_instance_);
  }

  void Swap(PrepareJute* other);

  // implements Message ----------------------------------------------

  inline PrepareJute* New() const PROTOBUF_FINAL { return New(NULL); }

  PrepareJute* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const PrepareJute& from);
  void MergeFrom(const PrepareJute& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(PrepareJute* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // int32 LeaderId = 1;
  void clear_leaderid();
  static const int kLeaderIdFieldNumber = 1;
  ::google::protobuf::int32 leaderid() const;
  void set_leaderid(::google::protobuf::int32 value);

  // int32 Replica = 2;
  void clear_replica();
  static const int kReplicaFieldNumber = 2;
  ::google::protobuf::int32 replica() const;
  void set_replica(::google::protobuf::int32 value);

  // int32 Instance = 3;
  void clear_instance();
  static const int kInstanceFieldNumber = 3;
  ::google::protobuf::int32 instance() const;
  void set_instance(::google::protobuf::int32 value);

  // int32 Ballot = 4;
  void clear_ballot();
  static const int kBallotFieldNumber = 4;
  ::google::protobuf::int32 ballot() const;
  void set_ballot(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:tkJute.PrepareJute)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int32 leaderid_;
  ::google::protobuf::int32 replica_;
  ::google::protobuf::int32 instance_;
  ::google::protobuf::int32 ballot_;
  mutable int _cached_size_;
  friend struct protobuf_protobuff_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class PrepareReplyJute : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:tkJute.PrepareReplyJute) */ {
 public:
  PrepareReplyJute();
  virtual ~PrepareReplyJute();

  PrepareReplyJute(const PrepareReplyJute& from);

  inline PrepareReplyJute& operator=(const PrepareReplyJute& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const PrepareReplyJute& default_instance();

  static inline const PrepareReplyJute* internal_default_instance() {
    return reinterpret_cast<const PrepareReplyJute*>(
               &_PrepareReplyJute_default_instance_);
  }

  void Swap(PrepareReplyJute* other);

  // implements Message ----------------------------------------------

  inline PrepareReplyJute* New() const PROTOBUF_FINAL { return New(NULL); }

  PrepareReplyJute* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const PrepareReplyJute& from);
  void MergeFrom(const PrepareReplyJute& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(PrepareReplyJute* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated int32 Deps = 9;
  int deps_size() const;
  void clear_deps();
  static const int kDepsFieldNumber = 9;
  ::google::protobuf::int32 deps(int index) const;
  void set_deps(int index, ::google::protobuf::int32 value);
  void add_deps(::google::protobuf::int32 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      deps() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_deps();

  // .tkJute.tk_command_jute cmd = 7;
  bool has_cmd() const;
  void clear_cmd();
  static const int kCmdFieldNumber = 7;
  const ::tkJute::tk_command_jute& cmd() const;
  ::tkJute::tk_command_jute* mutable_cmd();
  ::tkJute::tk_command_jute* release_cmd();
  void set_allocated_cmd(::tkJute::tk_command_jute* cmd);

  // int32 AcceptorId = 1;
  void clear_acceptorid();
  static const int kAcceptorIdFieldNumber = 1;
  ::google::protobuf::int32 acceptorid() const;
  void set_acceptorid(::google::protobuf::int32 value);

  // int32 Replica = 2;
  void clear_replica();
  static const int kReplicaFieldNumber = 2;
  ::google::protobuf::int32 replica() const;
  void set_replica(::google::protobuf::int32 value);

  // int32 Instance = 3;
  void clear_instance();
  static const int kInstanceFieldNumber = 3;
  ::google::protobuf::int32 instance() const;
  void set_instance(::google::protobuf::int32 value);

  // int32 Ok = 4;
  void clear_ok();
  static const int kOkFieldNumber = 4;
  ::google::protobuf::int32 ok() const;
  void set_ok(::google::protobuf::int32 value);

  // int32 Ballot = 5;
  void clear_ballot();
  static const int kBallotFieldNumber = 5;
  ::google::protobuf::int32 ballot() const;
  void set_ballot(::google::protobuf::int32 value);

  // int32 Status = 6;
  void clear_status();
  static const int kStatusFieldNumber = 6;
  ::google::protobuf::int32 status() const;
  void set_status(::google::protobuf::int32 value);

  // int32 Seq = 8;
  void clear_seq();
  static const int kSeqFieldNumber = 8;
  ::google::protobuf::int32 seq() const;
  void set_seq(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:tkJute.PrepareReplyJute)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > deps_;
  mutable int _deps_cached_byte_size_;
  ::tkJute::tk_command_jute* cmd_;
  ::google::protobuf::int32 acceptorid_;
  ::google::protobuf::int32 replica_;
  ::google::protobuf::int32 instance_;
  ::google::protobuf::int32 ok_;
  ::google::protobuf::int32 ballot_;
  ::google::protobuf::int32 status_;
  ::google::protobuf::int32 seq_;
  mutable int _cached_size_;
  friend struct protobuf_protobuff_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class PreAcceptJute : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:tkJute.PreAcceptJute) */ {
 public:
  PreAcceptJute();
  virtual ~PreAcceptJute();

  PreAcceptJute(const PreAcceptJute& from);

  inline PreAcceptJute& operator=(const PreAcceptJute& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const PreAcceptJute& default_instance();

  static inline const PreAcceptJute* internal_default_instance() {
    return reinterpret_cast<const PreAcceptJute*>(
               &_PreAcceptJute_default_instance_);
  }

  void Swap(PreAcceptJute* other);

  // implements Message ----------------------------------------------

  inline PreAcceptJute* New() const PROTOBUF_FINAL { return New(NULL); }

  PreAcceptJute* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const PreAcceptJute& from);
  void MergeFrom(const PreAcceptJute& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(PreAcceptJute* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated int32 Deps = 7;
  int deps_size() const;
  void clear_deps();
  static const int kDepsFieldNumber = 7;
  ::google::protobuf::int32 deps(int index) const;
  void set_deps(int index, ::google::protobuf::int32 value);
  void add_deps(::google::protobuf::int32 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      deps() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_deps();

  // .tkJute.tk_command_jute cmd = 5;
  bool has_cmd() const;
  void clear_cmd();
  static const int kCmdFieldNumber = 5;
  const ::tkJute::tk_command_jute& cmd() const;
  ::tkJute::tk_command_jute* mutable_cmd();
  ::tkJute::tk_command_jute* release_cmd();
  void set_allocated_cmd(::tkJute::tk_command_jute* cmd);

  // int32 LeaderId = 1;
  void clear_leaderid();
  static const int kLeaderIdFieldNumber = 1;
  ::google::protobuf::int32 leaderid() const;
  void set_leaderid(::google::protobuf::int32 value);

  // int32 Replica = 2;
  void clear_replica();
  static const int kReplicaFieldNumber = 2;
  ::google::protobuf::int32 replica() const;
  void set_replica(::google::protobuf::int32 value);

  // int32 Instance = 3;
  void clear_instance();
  static const int kInstanceFieldNumber = 3;
  ::google::protobuf::int32 instance() const;
  void set_instance(::google::protobuf::int32 value);

  // int32 Ballot = 4;
  void clear_ballot();
  static const int kBallotFieldNumber = 4;
  ::google::protobuf::int32 ballot() const;
  void set_ballot(::google::protobuf::int32 value);

  // int32 Seq = 6;
  void clear_seq();
  static const int kSeqFieldNumber = 6;
  ::google::protobuf::int32 seq() const;
  void set_seq(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:tkJute.PreAcceptJute)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > deps_;
  mutable int _deps_cached_byte_size_;
  ::tkJute::tk_command_jute* cmd_;
  ::google::protobuf::int32 leaderid_;
  ::google::protobuf::int32 replica_;
  ::google::protobuf::int32 instance_;
  ::google::protobuf::int32 ballot_;
  ::google::protobuf::int32 seq_;
  mutable int _cached_size_;
  friend struct protobuf_protobuff_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class PreAcceptReplyJute : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:tkJute.PreAcceptReplyJute) */ {
 public:
  PreAcceptReplyJute();
  virtual ~PreAcceptReplyJute();

  PreAcceptReplyJute(const PreAcceptReplyJute& from);

  inline PreAcceptReplyJute& operator=(const PreAcceptReplyJute& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const PreAcceptReplyJute& default_instance();

  static inline const PreAcceptReplyJute* internal_default_instance() {
    return reinterpret_cast<const PreAcceptReplyJute*>(
               &_PreAcceptReplyJute_default_instance_);
  }

  void Swap(PreAcceptReplyJute* other);

  // implements Message ----------------------------------------------

  inline PreAcceptReplyJute* New() const PROTOBUF_FINAL { return New(NULL); }

  PreAcceptReplyJute* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const PreAcceptReplyJute& from);
  void MergeFrom(const PreAcceptReplyJute& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(PreAcceptReplyJute* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated int32 Deps = 6;
  int deps_size() const;
  void clear_deps();
  static const int kDepsFieldNumber = 6;
  ::google::protobuf::int32 deps(int index) const;
  void set_deps(int index, ::google::protobuf::int32 value);
  void add_deps(::google::protobuf::int32 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      deps() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_deps();

  // repeated int32 CommittedDeps = 7;
  int committeddeps_size() const;
  void clear_committeddeps();
  static const int kCommittedDepsFieldNumber = 7;
  ::google::protobuf::int32 committeddeps(int index) const;
  void set_committeddeps(int index, ::google::protobuf::int32 value);
  void add_committeddeps(::google::protobuf::int32 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      committeddeps() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_committeddeps();

  // int32 Replica = 1;
  void clear_replica();
  static const int kReplicaFieldNumber = 1;
  ::google::protobuf::int32 replica() const;
  void set_replica(::google::protobuf::int32 value);

  // int32 Instance = 2;
  void clear_instance();
  static const int kInstanceFieldNumber = 2;
  ::google::protobuf::int32 instance() const;
  void set_instance(::google::protobuf::int32 value);

  // int32 Ok = 3;
  void clear_ok();
  static const int kOkFieldNumber = 3;
  ::google::protobuf::int32 ok() const;
  void set_ok(::google::protobuf::int32 value);

  // int32 Ballot = 4;
  void clear_ballot();
  static const int kBallotFieldNumber = 4;
  ::google::protobuf::int32 ballot() const;
  void set_ballot(::google::protobuf::int32 value);

  // int32 Seq = 5;
  void clear_seq();
  static const int kSeqFieldNumber = 5;
  ::google::protobuf::int32 seq() const;
  void set_seq(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:tkJute.PreAcceptReplyJute)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > deps_;
  mutable int _deps_cached_byte_size_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > committeddeps_;
  mutable int _committeddeps_cached_byte_size_;
  ::google::protobuf::int32 replica_;
  ::google::protobuf::int32 instance_;
  ::google::protobuf::int32 ok_;
  ::google::protobuf::int32 ballot_;
  ::google::protobuf::int32 seq_;
  mutable int _cached_size_;
  friend struct protobuf_protobuff_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class PreAcceptOkJute : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:tkJute.PreAcceptOkJute) */ {
 public:
  PreAcceptOkJute();
  virtual ~PreAcceptOkJute();

  PreAcceptOkJute(const PreAcceptOkJute& from);

  inline PreAcceptOkJute& operator=(const PreAcceptOkJute& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const PreAcceptOkJute& default_instance();

  static inline const PreAcceptOkJute* internal_default_instance() {
    return reinterpret_cast<const PreAcceptOkJute*>(
               &_PreAcceptOkJute_default_instance_);
  }

  void Swap(PreAcceptOkJute* other);

  // implements Message ----------------------------------------------

  inline PreAcceptOkJute* New() const PROTOBUF_FINAL { return New(NULL); }

  PreAcceptOkJute* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const PreAcceptOkJute& from);
  void MergeFrom(const PreAcceptOkJute& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(PreAcceptOkJute* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // int32 Instance = 1;
  void clear_instance();
  static const int kInstanceFieldNumber = 1;
  ::google::protobuf::int32 instance() const;
  void set_instance(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:tkJute.PreAcceptOkJute)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int32 instance_;
  mutable int _cached_size_;
  friend struct protobuf_protobuff_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class AcceptJute : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:tkJute.AcceptJute) */ {
 public:
  AcceptJute();
  virtual ~AcceptJute();

  AcceptJute(const AcceptJute& from);

  inline AcceptJute& operator=(const AcceptJute& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const AcceptJute& default_instance();

  static inline const AcceptJute* internal_default_instance() {
    return reinterpret_cast<const AcceptJute*>(
               &_AcceptJute_default_instance_);
  }

  void Swap(AcceptJute* other);

  // implements Message ----------------------------------------------

  inline AcceptJute* New() const PROTOBUF_FINAL { return New(NULL); }

  AcceptJute* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const AcceptJute& from);
  void MergeFrom(const AcceptJute& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(AcceptJute* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated int32 Deps = 7;
  int deps_size() const;
  void clear_deps();
  static const int kDepsFieldNumber = 7;
  ::google::protobuf::int32 deps(int index) const;
  void set_deps(int index, ::google::protobuf::int32 value);
  void add_deps(::google::protobuf::int32 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      deps() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_deps();

  // int32 LeaderId = 1;
  void clear_leaderid();
  static const int kLeaderIdFieldNumber = 1;
  ::google::protobuf::int32 leaderid() const;
  void set_leaderid(::google::protobuf::int32 value);

  // int32 Replica = 2;
  void clear_replica();
  static const int kReplicaFieldNumber = 2;
  ::google::protobuf::int32 replica() const;
  void set_replica(::google::protobuf::int32 value);

  // int32 Instance = 3;
  void clear_instance();
  static const int kInstanceFieldNumber = 3;
  ::google::protobuf::int32 instance() const;
  void set_instance(::google::protobuf::int32 value);

  // int32 Ballot = 4;
  void clear_ballot();
  static const int kBallotFieldNumber = 4;
  ::google::protobuf::int32 ballot() const;
  void set_ballot(::google::protobuf::int32 value);

  // int32 Count = 5;
  void clear_count();
  static const int kCountFieldNumber = 5;
  ::google::protobuf::int32 count() const;
  void set_count(::google::protobuf::int32 value);

  // int32 Seq = 6;
  void clear_seq();
  static const int kSeqFieldNumber = 6;
  ::google::protobuf::int32 seq() const;
  void set_seq(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:tkJute.AcceptJute)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > deps_;
  mutable int _deps_cached_byte_size_;
  ::google::protobuf::int32 leaderid_;
  ::google::protobuf::int32 replica_;
  ::google::protobuf::int32 instance_;
  ::google::protobuf::int32 ballot_;
  ::google::protobuf::int32 count_;
  ::google::protobuf::int32 seq_;
  mutable int _cached_size_;
  friend struct protobuf_protobuff_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class AcceptReplyJute : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:tkJute.AcceptReplyJute) */ {
 public:
  AcceptReplyJute();
  virtual ~AcceptReplyJute();

  AcceptReplyJute(const AcceptReplyJute& from);

  inline AcceptReplyJute& operator=(const AcceptReplyJute& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const AcceptReplyJute& default_instance();

  static inline const AcceptReplyJute* internal_default_instance() {
    return reinterpret_cast<const AcceptReplyJute*>(
               &_AcceptReplyJute_default_instance_);
  }

  void Swap(AcceptReplyJute* other);

  // implements Message ----------------------------------------------

  inline AcceptReplyJute* New() const PROTOBUF_FINAL { return New(NULL); }

  AcceptReplyJute* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const AcceptReplyJute& from);
  void MergeFrom(const AcceptReplyJute& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(AcceptReplyJute* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // int32 Replica = 1;
  void clear_replica();
  static const int kReplicaFieldNumber = 1;
  ::google::protobuf::int32 replica() const;
  void set_replica(::google::protobuf::int32 value);

  // int32 Instance = 2;
  void clear_instance();
  static const int kInstanceFieldNumber = 2;
  ::google::protobuf::int32 instance() const;
  void set_instance(::google::protobuf::int32 value);

  // int32 Ok = 3;
  void clear_ok();
  static const int kOkFieldNumber = 3;
  ::google::protobuf::int32 ok() const;
  void set_ok(::google::protobuf::int32 value);

  // int32 Ballot = 4;
  void clear_ballot();
  static const int kBallotFieldNumber = 4;
  ::google::protobuf::int32 ballot() const;
  void set_ballot(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:tkJute.AcceptReplyJute)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int32 replica_;
  ::google::protobuf::int32 instance_;
  ::google::protobuf::int32 ok_;
  ::google::protobuf::int32 ballot_;
  mutable int _cached_size_;
  friend struct protobuf_protobuff_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class CommitJute : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:tkJute.CommitJute) */ {
 public:
  CommitJute();
  virtual ~CommitJute();

  CommitJute(const CommitJute& from);

  inline CommitJute& operator=(const CommitJute& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const CommitJute& default_instance();

  static inline const CommitJute* internal_default_instance() {
    return reinterpret_cast<const CommitJute*>(
               &_CommitJute_default_instance_);
  }

  void Swap(CommitJute* other);

  // implements Message ----------------------------------------------

  inline CommitJute* New() const PROTOBUF_FINAL { return New(NULL); }

  CommitJute* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const CommitJute& from);
  void MergeFrom(const CommitJute& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(CommitJute* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated int32 Deps = 6;
  int deps_size() const;
  void clear_deps();
  static const int kDepsFieldNumber = 6;
  ::google::protobuf::int32 deps(int index) const;
  void set_deps(int index, ::google::protobuf::int32 value);
  void add_deps(::google::protobuf::int32 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      deps() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_deps();

  // .tkJute.tk_command_jute cmd = 4;
  bool has_cmd() const;
  void clear_cmd();
  static const int kCmdFieldNumber = 4;
  const ::tkJute::tk_command_jute& cmd() const;
  ::tkJute::tk_command_jute* mutable_cmd();
  ::tkJute::tk_command_jute* release_cmd();
  void set_allocated_cmd(::tkJute::tk_command_jute* cmd);

  // int32 LeaderId = 1;
  void clear_leaderid();
  static const int kLeaderIdFieldNumber = 1;
  ::google::protobuf::int32 leaderid() const;
  void set_leaderid(::google::protobuf::int32 value);

  // int32 Replica = 2;
  void clear_replica();
  static const int kReplicaFieldNumber = 2;
  ::google::protobuf::int32 replica() const;
  void set_replica(::google::protobuf::int32 value);

  // int32 Instance = 3;
  void clear_instance();
  static const int kInstanceFieldNumber = 3;
  ::google::protobuf::int32 instance() const;
  void set_instance(::google::protobuf::int32 value);

  // int32 Seq = 5;
  void clear_seq();
  static const int kSeqFieldNumber = 5;
  ::google::protobuf::int32 seq() const;
  void set_seq(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:tkJute.CommitJute)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > deps_;
  mutable int _deps_cached_byte_size_;
  ::tkJute::tk_command_jute* cmd_;
  ::google::protobuf::int32 leaderid_;
  ::google::protobuf::int32 replica_;
  ::google::protobuf::int32 instance_;
  ::google::protobuf::int32 seq_;
  mutable int _cached_size_;
  friend struct protobuf_protobuff_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class CommitShortJute : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:tkJute.CommitShortJute) */ {
 public:
  CommitShortJute();
  virtual ~CommitShortJute();

  CommitShortJute(const CommitShortJute& from);

  inline CommitShortJute& operator=(const CommitShortJute& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const CommitShortJute& default_instance();

  static inline const CommitShortJute* internal_default_instance() {
    return reinterpret_cast<const CommitShortJute*>(
               &_CommitShortJute_default_instance_);
  }

  void Swap(CommitShortJute* other);

  // implements Message ----------------------------------------------

  inline CommitShortJute* New() const PROTOBUF_FINAL { return New(NULL); }

  CommitShortJute* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const CommitShortJute& from);
  void MergeFrom(const CommitShortJute& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(CommitShortJute* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated int32 Deps = 6;
  int deps_size() const;
  void clear_deps();
  static const int kDepsFieldNumber = 6;
  ::google::protobuf::int32 deps(int index) const;
  void set_deps(int index, ::google::protobuf::int32 value);
  void add_deps(::google::protobuf::int32 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      deps() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_deps();

  // int32 LeaderId = 1;
  void clear_leaderid();
  static const int kLeaderIdFieldNumber = 1;
  ::google::protobuf::int32 leaderid() const;
  void set_leaderid(::google::protobuf::int32 value);

  // int32 Replica = 2;
  void clear_replica();
  static const int kReplicaFieldNumber = 2;
  ::google::protobuf::int32 replica() const;
  void set_replica(::google::protobuf::int32 value);

  // int32 Instance = 3;
  void clear_instance();
  static const int kInstanceFieldNumber = 3;
  ::google::protobuf::int32 instance() const;
  void set_instance(::google::protobuf::int32 value);

  // int32 Count = 4;
  void clear_count();
  static const int kCountFieldNumber = 4;
  ::google::protobuf::int32 count() const;
  void set_count(::google::protobuf::int32 value);

  // int32 Seq = 5;
  void clear_seq();
  static const int kSeqFieldNumber = 5;
  ::google::protobuf::int32 seq() const;
  void set_seq(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:tkJute.CommitShortJute)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > deps_;
  mutable int _deps_cached_byte_size_;
  ::google::protobuf::int32 leaderid_;
  ::google::protobuf::int32 replica_;
  ::google::protobuf::int32 instance_;
  ::google::protobuf::int32 count_;
  ::google::protobuf::int32 seq_;
  mutable int _cached_size_;
  friend struct protobuf_protobuff_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class TryPreAcceptJute : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:tkJute.TryPreAcceptJute) */ {
 public:
  TryPreAcceptJute();
  virtual ~TryPreAcceptJute();

  TryPreAcceptJute(const TryPreAcceptJute& from);

  inline TryPreAcceptJute& operator=(const TryPreAcceptJute& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const TryPreAcceptJute& default_instance();

  static inline const TryPreAcceptJute* internal_default_instance() {
    return reinterpret_cast<const TryPreAcceptJute*>(
               &_TryPreAcceptJute_default_instance_);
  }

  void Swap(TryPreAcceptJute* other);

  // implements Message ----------------------------------------------

  inline TryPreAcceptJute* New() const PROTOBUF_FINAL { return New(NULL); }

  TryPreAcceptJute* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const TryPreAcceptJute& from);
  void MergeFrom(const TryPreAcceptJute& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(TryPreAcceptJute* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated int32 Deps = 7;
  int deps_size() const;
  void clear_deps();
  static const int kDepsFieldNumber = 7;
  ::google::protobuf::int32 deps(int index) const;
  void set_deps(int index, ::google::protobuf::int32 value);
  void add_deps(::google::protobuf::int32 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      deps() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_deps();

  // .tkJute.tk_command_jute cmd = 5;
  bool has_cmd() const;
  void clear_cmd();
  static const int kCmdFieldNumber = 5;
  const ::tkJute::tk_command_jute& cmd() const;
  ::tkJute::tk_command_jute* mutable_cmd();
  ::tkJute::tk_command_jute* release_cmd();
  void set_allocated_cmd(::tkJute::tk_command_jute* cmd);

  // int32 LeaderId = 1;
  void clear_leaderid();
  static const int kLeaderIdFieldNumber = 1;
  ::google::protobuf::int32 leaderid() const;
  void set_leaderid(::google::protobuf::int32 value);

  // int32 Replica = 2;
  void clear_replica();
  static const int kReplicaFieldNumber = 2;
  ::google::protobuf::int32 replica() const;
  void set_replica(::google::protobuf::int32 value);

  // int32 Instance = 3;
  void clear_instance();
  static const int kInstanceFieldNumber = 3;
  ::google::protobuf::int32 instance() const;
  void set_instance(::google::protobuf::int32 value);

  // int32 Ballot = 4;
  void clear_ballot();
  static const int kBallotFieldNumber = 4;
  ::google::protobuf::int32 ballot() const;
  void set_ballot(::google::protobuf::int32 value);

  // int32 Seq = 6;
  void clear_seq();
  static const int kSeqFieldNumber = 6;
  ::google::protobuf::int32 seq() const;
  void set_seq(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:tkJute.TryPreAcceptJute)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > deps_;
  mutable int _deps_cached_byte_size_;
  ::tkJute::tk_command_jute* cmd_;
  ::google::protobuf::int32 leaderid_;
  ::google::protobuf::int32 replica_;
  ::google::protobuf::int32 instance_;
  ::google::protobuf::int32 ballot_;
  ::google::protobuf::int32 seq_;
  mutable int _cached_size_;
  friend struct protobuf_protobuff_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class TryPreAcceptReplyJute : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:tkJute.TryPreAcceptReplyJute) */ {
 public:
  TryPreAcceptReplyJute();
  virtual ~TryPreAcceptReplyJute();

  TryPreAcceptReplyJute(const TryPreAcceptReplyJute& from);

  inline TryPreAcceptReplyJute& operator=(const TryPreAcceptReplyJute& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const TryPreAcceptReplyJute& default_instance();

  static inline const TryPreAcceptReplyJute* internal_default_instance() {
    return reinterpret_cast<const TryPreAcceptReplyJute*>(
               &_TryPreAcceptReplyJute_default_instance_);
  }

  void Swap(TryPreAcceptReplyJute* other);

  // implements Message ----------------------------------------------

  inline TryPreAcceptReplyJute* New() const PROTOBUF_FINAL { return New(NULL); }

  TryPreAcceptReplyJute* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const TryPreAcceptReplyJute& from);
  void MergeFrom(const TryPreAcceptReplyJute& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(TryPreAcceptReplyJute* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // int32 AcceptorId = 1;
  void clear_acceptorid();
  static const int kAcceptorIdFieldNumber = 1;
  ::google::protobuf::int32 acceptorid() const;
  void set_acceptorid(::google::protobuf::int32 value);

  // int32 Replica = 2;
  void clear_replica();
  static const int kReplicaFieldNumber = 2;
  ::google::protobuf::int32 replica() const;
  void set_replica(::google::protobuf::int32 value);

  // int32 Instance = 3;
  void clear_instance();
  static const int kInstanceFieldNumber = 3;
  ::google::protobuf::int32 instance() const;
  void set_instance(::google::protobuf::int32 value);

  // int32 Ok = 4;
  void clear_ok();
  static const int kOkFieldNumber = 4;
  ::google::protobuf::int32 ok() const;
  void set_ok(::google::protobuf::int32 value);

  // int32 Ballot = 5;
  void clear_ballot();
  static const int kBallotFieldNumber = 5;
  ::google::protobuf::int32 ballot() const;
  void set_ballot(::google::protobuf::int32 value);

  // int32 ConfilctReplica = 6;
  void clear_confilctreplica();
  static const int kConfilctReplicaFieldNumber = 6;
  ::google::protobuf::int32 confilctreplica() const;
  void set_confilctreplica(::google::protobuf::int32 value);

  // int32 ConfilctInstance = 7;
  void clear_confilctinstance();
  static const int kConfilctInstanceFieldNumber = 7;
  ::google::protobuf::int32 confilctinstance() const;
  void set_confilctinstance(::google::protobuf::int32 value);

  // int32 ConfilctStatus = 8;
  void clear_confilctstatus();
  static const int kConfilctStatusFieldNumber = 8;
  ::google::protobuf::int32 confilctstatus() const;
  void set_confilctstatus(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:tkJute.TryPreAcceptReplyJute)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int32 acceptorid_;
  ::google::protobuf::int32 replica_;
  ::google::protobuf::int32 instance_;
  ::google::protobuf::int32 ok_;
  ::google::protobuf::int32 ballot_;
  ::google::protobuf::int32 confilctreplica_;
  ::google::protobuf::int32 confilctinstance_;
  ::google::protobuf::int32 confilctstatus_;
  mutable int _cached_size_;
  friend struct protobuf_protobuff_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// tk_command_jute

// int32 opcode = 1;
inline void tk_command_jute::clear_opcode() {
  opcode_ = 0;
}
inline ::google::protobuf::int32 tk_command_jute::opcode() const {
  // @@protoc_insertion_point(field_get:tkJute.tk_command_jute.opcode)
  return opcode_;
}
inline void tk_command_jute::set_opcode(::google::protobuf::int32 value) {
  
  opcode_ = value;
  // @@protoc_insertion_point(field_set:tkJute.tk_command_jute.opcode)
}

// string key = 2;
inline void tk_command_jute::clear_key() {
  key_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& tk_command_jute::key() const {
  // @@protoc_insertion_point(field_get:tkJute.tk_command_jute.key)
  return key_.GetNoArena();
}
inline void tk_command_jute::set_key(const ::std::string& value) {
  
  key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:tkJute.tk_command_jute.key)
}
#if LANG_CXX11
inline void tk_command_jute::set_key(::std::string&& value) {
  
  key_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:tkJute.tk_command_jute.key)
}
#endif
inline void tk_command_jute::set_key(const char* value) {
  
  key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:tkJute.tk_command_jute.key)
}
inline void tk_command_jute::set_key(const char* value, size_t size) {
  
  key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:tkJute.tk_command_jute.key)
}
inline ::std::string* tk_command_jute::mutable_key() {
  
  // @@protoc_insertion_point(field_mutable:tkJute.tk_command_jute.key)
  return key_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* tk_command_jute::release_key() {
  // @@protoc_insertion_point(field_release:tkJute.tk_command_jute.key)
  
  return key_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void tk_command_jute::set_allocated_key(::std::string* key) {
  if (key != NULL) {
    
  } else {
    
  }
  key_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), key);
  // @@protoc_insertion_point(field_set_allocated:tkJute.tk_command_jute.key)
}

// string val = 3;
inline void tk_command_jute::clear_val() {
  val_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& tk_command_jute::val() const {
  // @@protoc_insertion_point(field_get:tkJute.tk_command_jute.val)
  return val_.GetNoArena();
}
inline void tk_command_jute::set_val(const ::std::string& value) {
  
  val_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:tkJute.tk_command_jute.val)
}
#if LANG_CXX11
inline void tk_command_jute::set_val(::std::string&& value) {
  
  val_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:tkJute.tk_command_jute.val)
}
#endif
inline void tk_command_jute::set_val(const char* value) {
  
  val_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:tkJute.tk_command_jute.val)
}
inline void tk_command_jute::set_val(const char* value, size_t size) {
  
  val_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:tkJute.tk_command_jute.val)
}
inline ::std::string* tk_command_jute::mutable_val() {
  
  // @@protoc_insertion_point(field_mutable:tkJute.tk_command_jute.val)
  return val_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* tk_command_jute::release_val() {
  // @@protoc_insertion_point(field_release:tkJute.tk_command_jute.val)
  
  return val_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void tk_command_jute::set_allocated_val(::std::string* val) {
  if (val != NULL) {
    
  } else {
    
  }
  val_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), val);
  // @@protoc_insertion_point(field_set_allocated:tkJute.tk_command_jute.val)
}

// -------------------------------------------------------------------

// PrepareJute

// int32 LeaderId = 1;
inline void PrepareJute::clear_leaderid() {
  leaderid_ = 0;
}
inline ::google::protobuf::int32 PrepareJute::leaderid() const {
  // @@protoc_insertion_point(field_get:tkJute.PrepareJute.LeaderId)
  return leaderid_;
}
inline void PrepareJute::set_leaderid(::google::protobuf::int32 value) {
  
  leaderid_ = value;
  // @@protoc_insertion_point(field_set:tkJute.PrepareJute.LeaderId)
}

// int32 Replica = 2;
inline void PrepareJute::clear_replica() {
  replica_ = 0;
}
inline ::google::protobuf::int32 PrepareJute::replica() const {
  // @@protoc_insertion_point(field_get:tkJute.PrepareJute.Replica)
  return replica_;
}
inline void PrepareJute::set_replica(::google::protobuf::int32 value) {
  
  replica_ = value;
  // @@protoc_insertion_point(field_set:tkJute.PrepareJute.Replica)
}

// int32 Instance = 3;
inline void PrepareJute::clear_instance() {
  instance_ = 0;
}
inline ::google::protobuf::int32 PrepareJute::instance() const {
  // @@protoc_insertion_point(field_get:tkJute.PrepareJute.Instance)
  return instance_;
}
inline void PrepareJute::set_instance(::google::protobuf::int32 value) {
  
  instance_ = value;
  // @@protoc_insertion_point(field_set:tkJute.PrepareJute.Instance)
}

// int32 Ballot = 4;
inline void PrepareJute::clear_ballot() {
  ballot_ = 0;
}
inline ::google::protobuf::int32 PrepareJute::ballot() const {
  // @@protoc_insertion_point(field_get:tkJute.PrepareJute.Ballot)
  return ballot_;
}
inline void PrepareJute::set_ballot(::google::protobuf::int32 value) {
  
  ballot_ = value;
  // @@protoc_insertion_point(field_set:tkJute.PrepareJute.Ballot)
}

// -------------------------------------------------------------------

// PrepareReplyJute

// int32 AcceptorId = 1;
inline void PrepareReplyJute::clear_acceptorid() {
  acceptorid_ = 0;
}
inline ::google::protobuf::int32 PrepareReplyJute::acceptorid() const {
  // @@protoc_insertion_point(field_get:tkJute.PrepareReplyJute.AcceptorId)
  return acceptorid_;
}
inline void PrepareReplyJute::set_acceptorid(::google::protobuf::int32 value) {
  
  acceptorid_ = value;
  // @@protoc_insertion_point(field_set:tkJute.PrepareReplyJute.AcceptorId)
}

// int32 Replica = 2;
inline void PrepareReplyJute::clear_replica() {
  replica_ = 0;
}
inline ::google::protobuf::int32 PrepareReplyJute::replica() const {
  // @@protoc_insertion_point(field_get:tkJute.PrepareReplyJute.Replica)
  return replica_;
}
inline void PrepareReplyJute::set_replica(::google::protobuf::int32 value) {
  
  replica_ = value;
  // @@protoc_insertion_point(field_set:tkJute.PrepareReplyJute.Replica)
}

// int32 Instance = 3;
inline void PrepareReplyJute::clear_instance() {
  instance_ = 0;
}
inline ::google::protobuf::int32 PrepareReplyJute::instance() const {
  // @@protoc_insertion_point(field_get:tkJute.PrepareReplyJute.Instance)
  return instance_;
}
inline void PrepareReplyJute::set_instance(::google::protobuf::int32 value) {
  
  instance_ = value;
  // @@protoc_insertion_point(field_set:tkJute.PrepareReplyJute.Instance)
}

// int32 Ok = 4;
inline void PrepareReplyJute::clear_ok() {
  ok_ = 0;
}
inline ::google::protobuf::int32 PrepareReplyJute::ok() const {
  // @@protoc_insertion_point(field_get:tkJute.PrepareReplyJute.Ok)
  return ok_;
}
inline void PrepareReplyJute::set_ok(::google::protobuf::int32 value) {
  
  ok_ = value;
  // @@protoc_insertion_point(field_set:tkJute.PrepareReplyJute.Ok)
}

// int32 Ballot = 5;
inline void PrepareReplyJute::clear_ballot() {
  ballot_ = 0;
}
inline ::google::protobuf::int32 PrepareReplyJute::ballot() const {
  // @@protoc_insertion_point(field_get:tkJute.PrepareReplyJute.Ballot)
  return ballot_;
}
inline void PrepareReplyJute::set_ballot(::google::protobuf::int32 value) {
  
  ballot_ = value;
  // @@protoc_insertion_point(field_set:tkJute.PrepareReplyJute.Ballot)
}

// int32 Status = 6;
inline void PrepareReplyJute::clear_status() {
  status_ = 0;
}
inline ::google::protobuf::int32 PrepareReplyJute::status() const {
  // @@protoc_insertion_point(field_get:tkJute.PrepareReplyJute.Status)
  return status_;
}
inline void PrepareReplyJute::set_status(::google::protobuf::int32 value) {
  
  status_ = value;
  // @@protoc_insertion_point(field_set:tkJute.PrepareReplyJute.Status)
}

// .tkJute.tk_command_jute cmd = 7;
inline bool PrepareReplyJute::has_cmd() const {
  return this != internal_default_instance() && cmd_ != NULL;
}
inline void PrepareReplyJute::clear_cmd() {
  if (GetArenaNoVirtual() == NULL && cmd_ != NULL) delete cmd_;
  cmd_ = NULL;
}
inline const ::tkJute::tk_command_jute& PrepareReplyJute::cmd() const {
  // @@protoc_insertion_point(field_get:tkJute.PrepareReplyJute.cmd)
  return cmd_ != NULL ? *cmd_
                         : *::tkJute::tk_command_jute::internal_default_instance();
}
inline ::tkJute::tk_command_jute* PrepareReplyJute::mutable_cmd() {
  
  if (cmd_ == NULL) {
    cmd_ = new ::tkJute::tk_command_jute;
  }
  // @@protoc_insertion_point(field_mutable:tkJute.PrepareReplyJute.cmd)
  return cmd_;
}
inline ::tkJute::tk_command_jute* PrepareReplyJute::release_cmd() {
  // @@protoc_insertion_point(field_release:tkJute.PrepareReplyJute.cmd)
  
  ::tkJute::tk_command_jute* temp = cmd_;
  cmd_ = NULL;
  return temp;
}
inline void PrepareReplyJute::set_allocated_cmd(::tkJute::tk_command_jute* cmd) {
  delete cmd_;
  cmd_ = cmd;
  if (cmd) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:tkJute.PrepareReplyJute.cmd)
}

// int32 Seq = 8;
inline void PrepareReplyJute::clear_seq() {
  seq_ = 0;
}
inline ::google::protobuf::int32 PrepareReplyJute::seq() const {
  // @@protoc_insertion_point(field_get:tkJute.PrepareReplyJute.Seq)
  return seq_;
}
inline void PrepareReplyJute::set_seq(::google::protobuf::int32 value) {
  
  seq_ = value;
  // @@protoc_insertion_point(field_set:tkJute.PrepareReplyJute.Seq)
}

// repeated int32 Deps = 9;
inline int PrepareReplyJute::deps_size() const {
  return deps_.size();
}
inline void PrepareReplyJute::clear_deps() {
  deps_.Clear();
}
inline ::google::protobuf::int32 PrepareReplyJute::deps(int index) const {
  // @@protoc_insertion_point(field_get:tkJute.PrepareReplyJute.Deps)
  return deps_.Get(index);
}
inline void PrepareReplyJute::set_deps(int index, ::google::protobuf::int32 value) {
  deps_.Set(index, value);
  // @@protoc_insertion_point(field_set:tkJute.PrepareReplyJute.Deps)
}
inline void PrepareReplyJute::add_deps(::google::protobuf::int32 value) {
  deps_.Add(value);
  // @@protoc_insertion_point(field_add:tkJute.PrepareReplyJute.Deps)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
PrepareReplyJute::deps() const {
  // @@protoc_insertion_point(field_list:tkJute.PrepareReplyJute.Deps)
  return deps_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
PrepareReplyJute::mutable_deps() {
  // @@protoc_insertion_point(field_mutable_list:tkJute.PrepareReplyJute.Deps)
  return &deps_;
}

// -------------------------------------------------------------------

// PreAcceptJute

// int32 LeaderId = 1;
inline void PreAcceptJute::clear_leaderid() {
  leaderid_ = 0;
}
inline ::google::protobuf::int32 PreAcceptJute::leaderid() const {
  // @@protoc_insertion_point(field_get:tkJute.PreAcceptJute.LeaderId)
  return leaderid_;
}
inline void PreAcceptJute::set_leaderid(::google::protobuf::int32 value) {
  
  leaderid_ = value;
  // @@protoc_insertion_point(field_set:tkJute.PreAcceptJute.LeaderId)
}

// int32 Replica = 2;
inline void PreAcceptJute::clear_replica() {
  replica_ = 0;
}
inline ::google::protobuf::int32 PreAcceptJute::replica() const {
  // @@protoc_insertion_point(field_get:tkJute.PreAcceptJute.Replica)
  return replica_;
}
inline void PreAcceptJute::set_replica(::google::protobuf::int32 value) {
  
  replica_ = value;
  // @@protoc_insertion_point(field_set:tkJute.PreAcceptJute.Replica)
}

// int32 Instance = 3;
inline void PreAcceptJute::clear_instance() {
  instance_ = 0;
}
inline ::google::protobuf::int32 PreAcceptJute::instance() const {
  // @@protoc_insertion_point(field_get:tkJute.PreAcceptJute.Instance)
  return instance_;
}
inline void PreAcceptJute::set_instance(::google::protobuf::int32 value) {
  
  instance_ = value;
  // @@protoc_insertion_point(field_set:tkJute.PreAcceptJute.Instance)
}

// int32 Ballot = 4;
inline void PreAcceptJute::clear_ballot() {
  ballot_ = 0;
}
inline ::google::protobuf::int32 PreAcceptJute::ballot() const {
  // @@protoc_insertion_point(field_get:tkJute.PreAcceptJute.Ballot)
  return ballot_;
}
inline void PreAcceptJute::set_ballot(::google::protobuf::int32 value) {
  
  ballot_ = value;
  // @@protoc_insertion_point(field_set:tkJute.PreAcceptJute.Ballot)
}

// .tkJute.tk_command_jute cmd = 5;
inline bool PreAcceptJute::has_cmd() const {
  return this != internal_default_instance() && cmd_ != NULL;
}
inline void PreAcceptJute::clear_cmd() {
  if (GetArenaNoVirtual() == NULL && cmd_ != NULL) delete cmd_;
  cmd_ = NULL;
}
inline const ::tkJute::tk_command_jute& PreAcceptJute::cmd() const {
  // @@protoc_insertion_point(field_get:tkJute.PreAcceptJute.cmd)
  return cmd_ != NULL ? *cmd_
                         : *::tkJute::tk_command_jute::internal_default_instance();
}
inline ::tkJute::tk_command_jute* PreAcceptJute::mutable_cmd() {
  
  if (cmd_ == NULL) {
    cmd_ = new ::tkJute::tk_command_jute;
  }
  // @@protoc_insertion_point(field_mutable:tkJute.PreAcceptJute.cmd)
  return cmd_;
}
inline ::tkJute::tk_command_jute* PreAcceptJute::release_cmd() {
  // @@protoc_insertion_point(field_release:tkJute.PreAcceptJute.cmd)
  
  ::tkJute::tk_command_jute* temp = cmd_;
  cmd_ = NULL;
  return temp;
}
inline void PreAcceptJute::set_allocated_cmd(::tkJute::tk_command_jute* cmd) {
  delete cmd_;
  cmd_ = cmd;
  if (cmd) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:tkJute.PreAcceptJute.cmd)
}

// int32 Seq = 6;
inline void PreAcceptJute::clear_seq() {
  seq_ = 0;
}
inline ::google::protobuf::int32 PreAcceptJute::seq() const {
  // @@protoc_insertion_point(field_get:tkJute.PreAcceptJute.Seq)
  return seq_;
}
inline void PreAcceptJute::set_seq(::google::protobuf::int32 value) {
  
  seq_ = value;
  // @@protoc_insertion_point(field_set:tkJute.PreAcceptJute.Seq)
}

// repeated int32 Deps = 7;
inline int PreAcceptJute::deps_size() const {
  return deps_.size();
}
inline void PreAcceptJute::clear_deps() {
  deps_.Clear();
}
inline ::google::protobuf::int32 PreAcceptJute::deps(int index) const {
  // @@protoc_insertion_point(field_get:tkJute.PreAcceptJute.Deps)
  return deps_.Get(index);
}
inline void PreAcceptJute::set_deps(int index, ::google::protobuf::int32 value) {
  deps_.Set(index, value);
  // @@protoc_insertion_point(field_set:tkJute.PreAcceptJute.Deps)
}
inline void PreAcceptJute::add_deps(::google::protobuf::int32 value) {
  deps_.Add(value);
  // @@protoc_insertion_point(field_add:tkJute.PreAcceptJute.Deps)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
PreAcceptJute::deps() const {
  // @@protoc_insertion_point(field_list:tkJute.PreAcceptJute.Deps)
  return deps_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
PreAcceptJute::mutable_deps() {
  // @@protoc_insertion_point(field_mutable_list:tkJute.PreAcceptJute.Deps)
  return &deps_;
}

// -------------------------------------------------------------------

// PreAcceptReplyJute

// int32 Replica = 1;
inline void PreAcceptReplyJute::clear_replica() {
  replica_ = 0;
}
inline ::google::protobuf::int32 PreAcceptReplyJute::replica() const {
  // @@protoc_insertion_point(field_get:tkJute.PreAcceptReplyJute.Replica)
  return replica_;
}
inline void PreAcceptReplyJute::set_replica(::google::protobuf::int32 value) {
  
  replica_ = value;
  // @@protoc_insertion_point(field_set:tkJute.PreAcceptReplyJute.Replica)
}

// int32 Instance = 2;
inline void PreAcceptReplyJute::clear_instance() {
  instance_ = 0;
}
inline ::google::protobuf::int32 PreAcceptReplyJute::instance() const {
  // @@protoc_insertion_point(field_get:tkJute.PreAcceptReplyJute.Instance)
  return instance_;
}
inline void PreAcceptReplyJute::set_instance(::google::protobuf::int32 value) {
  
  instance_ = value;
  // @@protoc_insertion_point(field_set:tkJute.PreAcceptReplyJute.Instance)
}

// int32 Ok = 3;
inline void PreAcceptReplyJute::clear_ok() {
  ok_ = 0;
}
inline ::google::protobuf::int32 PreAcceptReplyJute::ok() const {
  // @@protoc_insertion_point(field_get:tkJute.PreAcceptReplyJute.Ok)
  return ok_;
}
inline void PreAcceptReplyJute::set_ok(::google::protobuf::int32 value) {
  
  ok_ = value;
  // @@protoc_insertion_point(field_set:tkJute.PreAcceptReplyJute.Ok)
}

// int32 Ballot = 4;
inline void PreAcceptReplyJute::clear_ballot() {
  ballot_ = 0;
}
inline ::google::protobuf::int32 PreAcceptReplyJute::ballot() const {
  // @@protoc_insertion_point(field_get:tkJute.PreAcceptReplyJute.Ballot)
  return ballot_;
}
inline void PreAcceptReplyJute::set_ballot(::google::protobuf::int32 value) {
  
  ballot_ = value;
  // @@protoc_insertion_point(field_set:tkJute.PreAcceptReplyJute.Ballot)
}

// int32 Seq = 5;
inline void PreAcceptReplyJute::clear_seq() {
  seq_ = 0;
}
inline ::google::protobuf::int32 PreAcceptReplyJute::seq() const {
  // @@protoc_insertion_point(field_get:tkJute.PreAcceptReplyJute.Seq)
  return seq_;
}
inline void PreAcceptReplyJute::set_seq(::google::protobuf::int32 value) {
  
  seq_ = value;
  // @@protoc_insertion_point(field_set:tkJute.PreAcceptReplyJute.Seq)
}

// repeated int32 Deps = 6;
inline int PreAcceptReplyJute::deps_size() const {
  return deps_.size();
}
inline void PreAcceptReplyJute::clear_deps() {
  deps_.Clear();
}
inline ::google::protobuf::int32 PreAcceptReplyJute::deps(int index) const {
  // @@protoc_insertion_point(field_get:tkJute.PreAcceptReplyJute.Deps)
  return deps_.Get(index);
}
inline void PreAcceptReplyJute::set_deps(int index, ::google::protobuf::int32 value) {
  deps_.Set(index, value);
  // @@protoc_insertion_point(field_set:tkJute.PreAcceptReplyJute.Deps)
}
inline void PreAcceptReplyJute::add_deps(::google::protobuf::int32 value) {
  deps_.Add(value);
  // @@protoc_insertion_point(field_add:tkJute.PreAcceptReplyJute.Deps)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
PreAcceptReplyJute::deps() const {
  // @@protoc_insertion_point(field_list:tkJute.PreAcceptReplyJute.Deps)
  return deps_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
PreAcceptReplyJute::mutable_deps() {
  // @@protoc_insertion_point(field_mutable_list:tkJute.PreAcceptReplyJute.Deps)
  return &deps_;
}

// repeated int32 CommittedDeps = 7;
inline int PreAcceptReplyJute::committeddeps_size() const {
  return committeddeps_.size();
}
inline void PreAcceptReplyJute::clear_committeddeps() {
  committeddeps_.Clear();
}
inline ::google::protobuf::int32 PreAcceptReplyJute::committeddeps(int index) const {
  // @@protoc_insertion_point(field_get:tkJute.PreAcceptReplyJute.CommittedDeps)
  return committeddeps_.Get(index);
}
inline void PreAcceptReplyJute::set_committeddeps(int index, ::google::protobuf::int32 value) {
  committeddeps_.Set(index, value);
  // @@protoc_insertion_point(field_set:tkJute.PreAcceptReplyJute.CommittedDeps)
}
inline void PreAcceptReplyJute::add_committeddeps(::google::protobuf::int32 value) {
  committeddeps_.Add(value);
  // @@protoc_insertion_point(field_add:tkJute.PreAcceptReplyJute.CommittedDeps)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
PreAcceptReplyJute::committeddeps() const {
  // @@protoc_insertion_point(field_list:tkJute.PreAcceptReplyJute.CommittedDeps)
  return committeddeps_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
PreAcceptReplyJute::mutable_committeddeps() {
  // @@protoc_insertion_point(field_mutable_list:tkJute.PreAcceptReplyJute.CommittedDeps)
  return &committeddeps_;
}

// -------------------------------------------------------------------

// PreAcceptOkJute

// int32 Instance = 1;
inline void PreAcceptOkJute::clear_instance() {
  instance_ = 0;
}
inline ::google::protobuf::int32 PreAcceptOkJute::instance() const {
  // @@protoc_insertion_point(field_get:tkJute.PreAcceptOkJute.Instance)
  return instance_;
}
inline void PreAcceptOkJute::set_instance(::google::protobuf::int32 value) {
  
  instance_ = value;
  // @@protoc_insertion_point(field_set:tkJute.PreAcceptOkJute.Instance)
}

// -------------------------------------------------------------------

// AcceptJute

// int32 LeaderId = 1;
inline void AcceptJute::clear_leaderid() {
  leaderid_ = 0;
}
inline ::google::protobuf::int32 AcceptJute::leaderid() const {
  // @@protoc_insertion_point(field_get:tkJute.AcceptJute.LeaderId)
  return leaderid_;
}
inline void AcceptJute::set_leaderid(::google::protobuf::int32 value) {
  
  leaderid_ = value;
  // @@protoc_insertion_point(field_set:tkJute.AcceptJute.LeaderId)
}

// int32 Replica = 2;
inline void AcceptJute::clear_replica() {
  replica_ = 0;
}
inline ::google::protobuf::int32 AcceptJute::replica() const {
  // @@protoc_insertion_point(field_get:tkJute.AcceptJute.Replica)
  return replica_;
}
inline void AcceptJute::set_replica(::google::protobuf::int32 value) {
  
  replica_ = value;
  // @@protoc_insertion_point(field_set:tkJute.AcceptJute.Replica)
}

// int32 Instance = 3;
inline void AcceptJute::clear_instance() {
  instance_ = 0;
}
inline ::google::protobuf::int32 AcceptJute::instance() const {
  // @@protoc_insertion_point(field_get:tkJute.AcceptJute.Instance)
  return instance_;
}
inline void AcceptJute::set_instance(::google::protobuf::int32 value) {
  
  instance_ = value;
  // @@protoc_insertion_point(field_set:tkJute.AcceptJute.Instance)
}

// int32 Ballot = 4;
inline void AcceptJute::clear_ballot() {
  ballot_ = 0;
}
inline ::google::protobuf::int32 AcceptJute::ballot() const {
  // @@protoc_insertion_point(field_get:tkJute.AcceptJute.Ballot)
  return ballot_;
}
inline void AcceptJute::set_ballot(::google::protobuf::int32 value) {
  
  ballot_ = value;
  // @@protoc_insertion_point(field_set:tkJute.AcceptJute.Ballot)
}

// int32 Count = 5;
inline void AcceptJute::clear_count() {
  count_ = 0;
}
inline ::google::protobuf::int32 AcceptJute::count() const {
  // @@protoc_insertion_point(field_get:tkJute.AcceptJute.Count)
  return count_;
}
inline void AcceptJute::set_count(::google::protobuf::int32 value) {
  
  count_ = value;
  // @@protoc_insertion_point(field_set:tkJute.AcceptJute.Count)
}

// int32 Seq = 6;
inline void AcceptJute::clear_seq() {
  seq_ = 0;
}
inline ::google::protobuf::int32 AcceptJute::seq() const {
  // @@protoc_insertion_point(field_get:tkJute.AcceptJute.Seq)
  return seq_;
}
inline void AcceptJute::set_seq(::google::protobuf::int32 value) {
  
  seq_ = value;
  // @@protoc_insertion_point(field_set:tkJute.AcceptJute.Seq)
}

// repeated int32 Deps = 7;
inline int AcceptJute::deps_size() const {
  return deps_.size();
}
inline void AcceptJute::clear_deps() {
  deps_.Clear();
}
inline ::google::protobuf::int32 AcceptJute::deps(int index) const {
  // @@protoc_insertion_point(field_get:tkJute.AcceptJute.Deps)
  return deps_.Get(index);
}
inline void AcceptJute::set_deps(int index, ::google::protobuf::int32 value) {
  deps_.Set(index, value);
  // @@protoc_insertion_point(field_set:tkJute.AcceptJute.Deps)
}
inline void AcceptJute::add_deps(::google::protobuf::int32 value) {
  deps_.Add(value);
  // @@protoc_insertion_point(field_add:tkJute.AcceptJute.Deps)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
AcceptJute::deps() const {
  // @@protoc_insertion_point(field_list:tkJute.AcceptJute.Deps)
  return deps_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
AcceptJute::mutable_deps() {
  // @@protoc_insertion_point(field_mutable_list:tkJute.AcceptJute.Deps)
  return &deps_;
}

// -------------------------------------------------------------------

// AcceptReplyJute

// int32 Replica = 1;
inline void AcceptReplyJute::clear_replica() {
  replica_ = 0;
}
inline ::google::protobuf::int32 AcceptReplyJute::replica() const {
  // @@protoc_insertion_point(field_get:tkJute.AcceptReplyJute.Replica)
  return replica_;
}
inline void AcceptReplyJute::set_replica(::google::protobuf::int32 value) {
  
  replica_ = value;
  // @@protoc_insertion_point(field_set:tkJute.AcceptReplyJute.Replica)
}

// int32 Instance = 2;
inline void AcceptReplyJute::clear_instance() {
  instance_ = 0;
}
inline ::google::protobuf::int32 AcceptReplyJute::instance() const {
  // @@protoc_insertion_point(field_get:tkJute.AcceptReplyJute.Instance)
  return instance_;
}
inline void AcceptReplyJute::set_instance(::google::protobuf::int32 value) {
  
  instance_ = value;
  // @@protoc_insertion_point(field_set:tkJute.AcceptReplyJute.Instance)
}

// int32 Ok = 3;
inline void AcceptReplyJute::clear_ok() {
  ok_ = 0;
}
inline ::google::protobuf::int32 AcceptReplyJute::ok() const {
  // @@protoc_insertion_point(field_get:tkJute.AcceptReplyJute.Ok)
  return ok_;
}
inline void AcceptReplyJute::set_ok(::google::protobuf::int32 value) {
  
  ok_ = value;
  // @@protoc_insertion_point(field_set:tkJute.AcceptReplyJute.Ok)
}

// int32 Ballot = 4;
inline void AcceptReplyJute::clear_ballot() {
  ballot_ = 0;
}
inline ::google::protobuf::int32 AcceptReplyJute::ballot() const {
  // @@protoc_insertion_point(field_get:tkJute.AcceptReplyJute.Ballot)
  return ballot_;
}
inline void AcceptReplyJute::set_ballot(::google::protobuf::int32 value) {
  
  ballot_ = value;
  // @@protoc_insertion_point(field_set:tkJute.AcceptReplyJute.Ballot)
}

// -------------------------------------------------------------------

// CommitJute

// int32 LeaderId = 1;
inline void CommitJute::clear_leaderid() {
  leaderid_ = 0;
}
inline ::google::protobuf::int32 CommitJute::leaderid() const {
  // @@protoc_insertion_point(field_get:tkJute.CommitJute.LeaderId)
  return leaderid_;
}
inline void CommitJute::set_leaderid(::google::protobuf::int32 value) {
  
  leaderid_ = value;
  // @@protoc_insertion_point(field_set:tkJute.CommitJute.LeaderId)
}

// int32 Replica = 2;
inline void CommitJute::clear_replica() {
  replica_ = 0;
}
inline ::google::protobuf::int32 CommitJute::replica() const {
  // @@protoc_insertion_point(field_get:tkJute.CommitJute.Replica)
  return replica_;
}
inline void CommitJute::set_replica(::google::protobuf::int32 value) {
  
  replica_ = value;
  // @@protoc_insertion_point(field_set:tkJute.CommitJute.Replica)
}

// int32 Instance = 3;
inline void CommitJute::clear_instance() {
  instance_ = 0;
}
inline ::google::protobuf::int32 CommitJute::instance() const {
  // @@protoc_insertion_point(field_get:tkJute.CommitJute.Instance)
  return instance_;
}
inline void CommitJute::set_instance(::google::protobuf::int32 value) {
  
  instance_ = value;
  // @@protoc_insertion_point(field_set:tkJute.CommitJute.Instance)
}

// .tkJute.tk_command_jute cmd = 4;
inline bool CommitJute::has_cmd() const {
  return this != internal_default_instance() && cmd_ != NULL;
}
inline void CommitJute::clear_cmd() {
  if (GetArenaNoVirtual() == NULL && cmd_ != NULL) delete cmd_;
  cmd_ = NULL;
}
inline const ::tkJute::tk_command_jute& CommitJute::cmd() const {
  // @@protoc_insertion_point(field_get:tkJute.CommitJute.cmd)
  return cmd_ != NULL ? *cmd_
                         : *::tkJute::tk_command_jute::internal_default_instance();
}
inline ::tkJute::tk_command_jute* CommitJute::mutable_cmd() {
  
  if (cmd_ == NULL) {
    cmd_ = new ::tkJute::tk_command_jute;
  }
  // @@protoc_insertion_point(field_mutable:tkJute.CommitJute.cmd)
  return cmd_;
}
inline ::tkJute::tk_command_jute* CommitJute::release_cmd() {
  // @@protoc_insertion_point(field_release:tkJute.CommitJute.cmd)
  
  ::tkJute::tk_command_jute* temp = cmd_;
  cmd_ = NULL;
  return temp;
}
inline void CommitJute::set_allocated_cmd(::tkJute::tk_command_jute* cmd) {
  delete cmd_;
  cmd_ = cmd;
  if (cmd) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:tkJute.CommitJute.cmd)
}

// int32 Seq = 5;
inline void CommitJute::clear_seq() {
  seq_ = 0;
}
inline ::google::protobuf::int32 CommitJute::seq() const {
  // @@protoc_insertion_point(field_get:tkJute.CommitJute.Seq)
  return seq_;
}
inline void CommitJute::set_seq(::google::protobuf::int32 value) {
  
  seq_ = value;
  // @@protoc_insertion_point(field_set:tkJute.CommitJute.Seq)
}

// repeated int32 Deps = 6;
inline int CommitJute::deps_size() const {
  return deps_.size();
}
inline void CommitJute::clear_deps() {
  deps_.Clear();
}
inline ::google::protobuf::int32 CommitJute::deps(int index) const {
  // @@protoc_insertion_point(field_get:tkJute.CommitJute.Deps)
  return deps_.Get(index);
}
inline void CommitJute::set_deps(int index, ::google::protobuf::int32 value) {
  deps_.Set(index, value);
  // @@protoc_insertion_point(field_set:tkJute.CommitJute.Deps)
}
inline void CommitJute::add_deps(::google::protobuf::int32 value) {
  deps_.Add(value);
  // @@protoc_insertion_point(field_add:tkJute.CommitJute.Deps)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
CommitJute::deps() const {
  // @@protoc_insertion_point(field_list:tkJute.CommitJute.Deps)
  return deps_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
CommitJute::mutable_deps() {
  // @@protoc_insertion_point(field_mutable_list:tkJute.CommitJute.Deps)
  return &deps_;
}

// -------------------------------------------------------------------

// CommitShortJute

// int32 LeaderId = 1;
inline void CommitShortJute::clear_leaderid() {
  leaderid_ = 0;
}
inline ::google::protobuf::int32 CommitShortJute::leaderid() const {
  // @@protoc_insertion_point(field_get:tkJute.CommitShortJute.LeaderId)
  return leaderid_;
}
inline void CommitShortJute::set_leaderid(::google::protobuf::int32 value) {
  
  leaderid_ = value;
  // @@protoc_insertion_point(field_set:tkJute.CommitShortJute.LeaderId)
}

// int32 Replica = 2;
inline void CommitShortJute::clear_replica() {
  replica_ = 0;
}
inline ::google::protobuf::int32 CommitShortJute::replica() const {
  // @@protoc_insertion_point(field_get:tkJute.CommitShortJute.Replica)
  return replica_;
}
inline void CommitShortJute::set_replica(::google::protobuf::int32 value) {
  
  replica_ = value;
  // @@protoc_insertion_point(field_set:tkJute.CommitShortJute.Replica)
}

// int32 Instance = 3;
inline void CommitShortJute::clear_instance() {
  instance_ = 0;
}
inline ::google::protobuf::int32 CommitShortJute::instance() const {
  // @@protoc_insertion_point(field_get:tkJute.CommitShortJute.Instance)
  return instance_;
}
inline void CommitShortJute::set_instance(::google::protobuf::int32 value) {
  
  instance_ = value;
  // @@protoc_insertion_point(field_set:tkJute.CommitShortJute.Instance)
}

// int32 Count = 4;
inline void CommitShortJute::clear_count() {
  count_ = 0;
}
inline ::google::protobuf::int32 CommitShortJute::count() const {
  // @@protoc_insertion_point(field_get:tkJute.CommitShortJute.Count)
  return count_;
}
inline void CommitShortJute::set_count(::google::protobuf::int32 value) {
  
  count_ = value;
  // @@protoc_insertion_point(field_set:tkJute.CommitShortJute.Count)
}

// int32 Seq = 5;
inline void CommitShortJute::clear_seq() {
  seq_ = 0;
}
inline ::google::protobuf::int32 CommitShortJute::seq() const {
  // @@protoc_insertion_point(field_get:tkJute.CommitShortJute.Seq)
  return seq_;
}
inline void CommitShortJute::set_seq(::google::protobuf::int32 value) {
  
  seq_ = value;
  // @@protoc_insertion_point(field_set:tkJute.CommitShortJute.Seq)
}

// repeated int32 Deps = 6;
inline int CommitShortJute::deps_size() const {
  return deps_.size();
}
inline void CommitShortJute::clear_deps() {
  deps_.Clear();
}
inline ::google::protobuf::int32 CommitShortJute::deps(int index) const {
  // @@protoc_insertion_point(field_get:tkJute.CommitShortJute.Deps)
  return deps_.Get(index);
}
inline void CommitShortJute::set_deps(int index, ::google::protobuf::int32 value) {
  deps_.Set(index, value);
  // @@protoc_insertion_point(field_set:tkJute.CommitShortJute.Deps)
}
inline void CommitShortJute::add_deps(::google::protobuf::int32 value) {
  deps_.Add(value);
  // @@protoc_insertion_point(field_add:tkJute.CommitShortJute.Deps)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
CommitShortJute::deps() const {
  // @@protoc_insertion_point(field_list:tkJute.CommitShortJute.Deps)
  return deps_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
CommitShortJute::mutable_deps() {
  // @@protoc_insertion_point(field_mutable_list:tkJute.CommitShortJute.Deps)
  return &deps_;
}

// -------------------------------------------------------------------

// TryPreAcceptJute

// int32 LeaderId = 1;
inline void TryPreAcceptJute::clear_leaderid() {
  leaderid_ = 0;
}
inline ::google::protobuf::int32 TryPreAcceptJute::leaderid() const {
  // @@protoc_insertion_point(field_get:tkJute.TryPreAcceptJute.LeaderId)
  return leaderid_;
}
inline void TryPreAcceptJute::set_leaderid(::google::protobuf::int32 value) {
  
  leaderid_ = value;
  // @@protoc_insertion_point(field_set:tkJute.TryPreAcceptJute.LeaderId)
}

// int32 Replica = 2;
inline void TryPreAcceptJute::clear_replica() {
  replica_ = 0;
}
inline ::google::protobuf::int32 TryPreAcceptJute::replica() const {
  // @@protoc_insertion_point(field_get:tkJute.TryPreAcceptJute.Replica)
  return replica_;
}
inline void TryPreAcceptJute::set_replica(::google::protobuf::int32 value) {
  
  replica_ = value;
  // @@protoc_insertion_point(field_set:tkJute.TryPreAcceptJute.Replica)
}

// int32 Instance = 3;
inline void TryPreAcceptJute::clear_instance() {
  instance_ = 0;
}
inline ::google::protobuf::int32 TryPreAcceptJute::instance() const {
  // @@protoc_insertion_point(field_get:tkJute.TryPreAcceptJute.Instance)
  return instance_;
}
inline void TryPreAcceptJute::set_instance(::google::protobuf::int32 value) {
  
  instance_ = value;
  // @@protoc_insertion_point(field_set:tkJute.TryPreAcceptJute.Instance)
}

// int32 Ballot = 4;
inline void TryPreAcceptJute::clear_ballot() {
  ballot_ = 0;
}
inline ::google::protobuf::int32 TryPreAcceptJute::ballot() const {
  // @@protoc_insertion_point(field_get:tkJute.TryPreAcceptJute.Ballot)
  return ballot_;
}
inline void TryPreAcceptJute::set_ballot(::google::protobuf::int32 value) {
  
  ballot_ = value;
  // @@protoc_insertion_point(field_set:tkJute.TryPreAcceptJute.Ballot)
}

// .tkJute.tk_command_jute cmd = 5;
inline bool TryPreAcceptJute::has_cmd() const {
  return this != internal_default_instance() && cmd_ != NULL;
}
inline void TryPreAcceptJute::clear_cmd() {
  if (GetArenaNoVirtual() == NULL && cmd_ != NULL) delete cmd_;
  cmd_ = NULL;
}
inline const ::tkJute::tk_command_jute& TryPreAcceptJute::cmd() const {
  // @@protoc_insertion_point(field_get:tkJute.TryPreAcceptJute.cmd)
  return cmd_ != NULL ? *cmd_
                         : *::tkJute::tk_command_jute::internal_default_instance();
}
inline ::tkJute::tk_command_jute* TryPreAcceptJute::mutable_cmd() {
  
  if (cmd_ == NULL) {
    cmd_ = new ::tkJute::tk_command_jute;
  }
  // @@protoc_insertion_point(field_mutable:tkJute.TryPreAcceptJute.cmd)
  return cmd_;
}
inline ::tkJute::tk_command_jute* TryPreAcceptJute::release_cmd() {
  // @@protoc_insertion_point(field_release:tkJute.TryPreAcceptJute.cmd)
  
  ::tkJute::tk_command_jute* temp = cmd_;
  cmd_ = NULL;
  return temp;
}
inline void TryPreAcceptJute::set_allocated_cmd(::tkJute::tk_command_jute* cmd) {
  delete cmd_;
  cmd_ = cmd;
  if (cmd) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:tkJute.TryPreAcceptJute.cmd)
}

// int32 Seq = 6;
inline void TryPreAcceptJute::clear_seq() {
  seq_ = 0;
}
inline ::google::protobuf::int32 TryPreAcceptJute::seq() const {
  // @@protoc_insertion_point(field_get:tkJute.TryPreAcceptJute.Seq)
  return seq_;
}
inline void TryPreAcceptJute::set_seq(::google::protobuf::int32 value) {
  
  seq_ = value;
  // @@protoc_insertion_point(field_set:tkJute.TryPreAcceptJute.Seq)
}

// repeated int32 Deps = 7;
inline int TryPreAcceptJute::deps_size() const {
  return deps_.size();
}
inline void TryPreAcceptJute::clear_deps() {
  deps_.Clear();
}
inline ::google::protobuf::int32 TryPreAcceptJute::deps(int index) const {
  // @@protoc_insertion_point(field_get:tkJute.TryPreAcceptJute.Deps)
  return deps_.Get(index);
}
inline void TryPreAcceptJute::set_deps(int index, ::google::protobuf::int32 value) {
  deps_.Set(index, value);
  // @@protoc_insertion_point(field_set:tkJute.TryPreAcceptJute.Deps)
}
inline void TryPreAcceptJute::add_deps(::google::protobuf::int32 value) {
  deps_.Add(value);
  // @@protoc_insertion_point(field_add:tkJute.TryPreAcceptJute.Deps)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
TryPreAcceptJute::deps() const {
  // @@protoc_insertion_point(field_list:tkJute.TryPreAcceptJute.Deps)
  return deps_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
TryPreAcceptJute::mutable_deps() {
  // @@protoc_insertion_point(field_mutable_list:tkJute.TryPreAcceptJute.Deps)
  return &deps_;
}

// -------------------------------------------------------------------

// TryPreAcceptReplyJute

// int32 AcceptorId = 1;
inline void TryPreAcceptReplyJute::clear_acceptorid() {
  acceptorid_ = 0;
}
inline ::google::protobuf::int32 TryPreAcceptReplyJute::acceptorid() const {
  // @@protoc_insertion_point(field_get:tkJute.TryPreAcceptReplyJute.AcceptorId)
  return acceptorid_;
}
inline void TryPreAcceptReplyJute::set_acceptorid(::google::protobuf::int32 value) {
  
  acceptorid_ = value;
  // @@protoc_insertion_point(field_set:tkJute.TryPreAcceptReplyJute.AcceptorId)
}

// int32 Replica = 2;
inline void TryPreAcceptReplyJute::clear_replica() {
  replica_ = 0;
}
inline ::google::protobuf::int32 TryPreAcceptReplyJute::replica() const {
  // @@protoc_insertion_point(field_get:tkJute.TryPreAcceptReplyJute.Replica)
  return replica_;
}
inline void TryPreAcceptReplyJute::set_replica(::google::protobuf::int32 value) {
  
  replica_ = value;
  // @@protoc_insertion_point(field_set:tkJute.TryPreAcceptReplyJute.Replica)
}

// int32 Instance = 3;
inline void TryPreAcceptReplyJute::clear_instance() {
  instance_ = 0;
}
inline ::google::protobuf::int32 TryPreAcceptReplyJute::instance() const {
  // @@protoc_insertion_point(field_get:tkJute.TryPreAcceptReplyJute.Instance)
  return instance_;
}
inline void TryPreAcceptReplyJute::set_instance(::google::protobuf::int32 value) {
  
  instance_ = value;
  // @@protoc_insertion_point(field_set:tkJute.TryPreAcceptReplyJute.Instance)
}

// int32 Ok = 4;
inline void TryPreAcceptReplyJute::clear_ok() {
  ok_ = 0;
}
inline ::google::protobuf::int32 TryPreAcceptReplyJute::ok() const {
  // @@protoc_insertion_point(field_get:tkJute.TryPreAcceptReplyJute.Ok)
  return ok_;
}
inline void TryPreAcceptReplyJute::set_ok(::google::protobuf::int32 value) {
  
  ok_ = value;
  // @@protoc_insertion_point(field_set:tkJute.TryPreAcceptReplyJute.Ok)
}

// int32 Ballot = 5;
inline void TryPreAcceptReplyJute::clear_ballot() {
  ballot_ = 0;
}
inline ::google::protobuf::int32 TryPreAcceptReplyJute::ballot() const {
  // @@protoc_insertion_point(field_get:tkJute.TryPreAcceptReplyJute.Ballot)
  return ballot_;
}
inline void TryPreAcceptReplyJute::set_ballot(::google::protobuf::int32 value) {
  
  ballot_ = value;
  // @@protoc_insertion_point(field_set:tkJute.TryPreAcceptReplyJute.Ballot)
}

// int32 ConfilctReplica = 6;
inline void TryPreAcceptReplyJute::clear_confilctreplica() {
  confilctreplica_ = 0;
}
inline ::google::protobuf::int32 TryPreAcceptReplyJute::confilctreplica() const {
  // @@protoc_insertion_point(field_get:tkJute.TryPreAcceptReplyJute.ConfilctReplica)
  return confilctreplica_;
}
inline void TryPreAcceptReplyJute::set_confilctreplica(::google::protobuf::int32 value) {
  
  confilctreplica_ = value;
  // @@protoc_insertion_point(field_set:tkJute.TryPreAcceptReplyJute.ConfilctReplica)
}

// int32 ConfilctInstance = 7;
inline void TryPreAcceptReplyJute::clear_confilctinstance() {
  confilctinstance_ = 0;
}
inline ::google::protobuf::int32 TryPreAcceptReplyJute::confilctinstance() const {
  // @@protoc_insertion_point(field_get:tkJute.TryPreAcceptReplyJute.ConfilctInstance)
  return confilctinstance_;
}
inline void TryPreAcceptReplyJute::set_confilctinstance(::google::protobuf::int32 value) {
  
  confilctinstance_ = value;
  // @@protoc_insertion_point(field_set:tkJute.TryPreAcceptReplyJute.ConfilctInstance)
}

// int32 ConfilctStatus = 8;
inline void TryPreAcceptReplyJute::clear_confilctstatus() {
  confilctstatus_ = 0;
}
inline ::google::protobuf::int32 TryPreAcceptReplyJute::confilctstatus() const {
  // @@protoc_insertion_point(field_get:tkJute.TryPreAcceptReplyJute.ConfilctStatus)
  return confilctstatus_;
}
inline void TryPreAcceptReplyJute::set_confilctstatus(::google::protobuf::int32 value) {
  
  confilctstatus_ = value;
  // @@protoc_insertion_point(field_set:tkJute.TryPreAcceptReplyJute.ConfilctStatus)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


}  // namespace tkJute

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_protobuff_2eproto__INCLUDED
